version: '3'

volumes:
  ark-data:

services:
  server:
    restart: always
    container_name: ark_server
    image: jfvoliveira2001/ark-server:1.0.1
    # If you want to build from fresh source every "docker-compose up" ...
    # ... remove the "image:"-key and uncomment the following two lines:
    build:
      context: ../.
    volumes:
      # # This setup is necessary if you have to download a non-anonymous appID/modID
      # ${STEAM_SESSION_VOLUME}:/home/steam/Steam
      - ./data:/app
    stop_grace_period: 1m30s
    environment:
      # # This setup is necessary if you have to download a non-anonymous appID/modID
      #- STEAM_LOGIN=${STEAM_LOGIN}
      - SESSION_NAME=OLAA
      - SERVER_MAP=TheIsland
      - SERVER_PASSWORD=
      - ADMIN_PASSWORD=123
      - MAX_PLAYERS=4
    ports:
      # Port for connections from ARK game client
      - "7777:7777/udp"
      # Raw UDP socket port (always Game client port +1
      - "7778:7778/udp"
      # RCON management port
      - "27020:27020/tcp"
      # Steam's server-list port
      - "27015:27015/udp"
    networks:
      - default
